### ISSUE TITLE
srcript halts and give exception while return error array.

### ISSUE THREAD

**Issue by muttou** [CreativeDream/php-uploader#10]
Uncaught SyntaxError: Unexpected token < in JSON at position 0

this happen when non allowed file types upload with this plugin. kindly assist. thanks for your quick response.

**Comment by CreativeDream** [comment]
@muttou becouse it sends non JSON response. You need to do echo json_encode(...);

**Comment by muttou** [comment]
if($data['hasErrors']){
        $errors = $data['errors'];
        echo json_encode($errors);
    }

that sample code is taken from sample files along with the download.. thanks for your support again.
