### ISSUE TITLE
Option to not overwrite existing files

### ISSUE THREAD

**Issue by primehalo** [CreativeDream/php-uploader#2]
I think it would be useful to have an option which would automatically rename a file being uploaded if a file of the same name already exists, such as appending " (1)" to the file name.

**Comment by CreativeDream** [comment]
good ideea

**Comment by CreativeDream** [comment]
@primehalo will be fixed in version [2.0](https://github.com/CreativeDream/jQuery.filer/issues/59).

It will work like this: `'replace' => false` to get files as `filename (1).extension`

Thanks for ideea.

**Comment by CreativeDream** [comment]
@primehalo fixed https://github.com/CreativeDream/php-uploader 0.3
