### ISSUE TITLE
Image title issue in upload folder

### ISSUE THREAD

**Issue by brst-dev** [CreativeDream/php-uploader#4]
Hello
Thanks for this awesome plugin.
I am using 'title' => array('{{file_name}}_{{timestamp}}') to set image name.
But if my image has a name like img_name.PNG(CAPS LOCK IN TYPE OF IMAGE) then it gives name like img_name.PN_timestamp.png

Please help 

Thanks 
Brst dev

**Comment by CreativeDream** [comment]
@brst-dev will be fixed in version [2.0](https://github.com/CreativeDream/jQuery.filer/issues/59).

It will work like this: `'title' => array('{{file_name}}_{{timestamp}}{{.extension}}')`

**Comment by CreativeDream** [comment]
@brst-dev https://github.com/CreativeDream/php-uploader 0.3 - fixed
