### ISSUE TITLE
Additional file information

### ISSUE THREAD

**Issue by trf000** [CreativeDream/php-uploader#5]
I've figured out how to pre-pend my filenames with both a logged in user_id and a random character generator. This pretty much ensures I get a unique file name.

But I also need a proper title for the database. is there a way to add a input field after the files are selected, but before they are submitted? It can either be a textfield or a select box with pre-determined titles.

**Comment by CreativeDream** [comment]
@trf000 what do you want to do?

**Comment by trf000** [comment]
Sorry, I missed this. Busy time of the year.

I want to upload multiple files, inserting a record into the database with unique title for each file. So when viewing the files I see "File Title" instead of "00912345_form.pdf" when viewing them with my web application.
