### ISSUE TITLE
Multiple Files Upload issue in using addmore option.

### ISSUE THREAD

**Issue by arif-medialinker** [CreativeDream/php-uploader#7]
Hi,

I have found an issue in Multiple file upload using option addMore: true,

If you add files one by one into file upload, and then when you submit form you get only last file in $_FILES array. 

![capture1](https://cloud.githubusercontent.com/assets/21219058/17929708/ae2812e0-6a1b-11e6-977c-b9523ec2c777.PNG)
![capture2](https://cloud.githubusercontent.com/assets/21219058/17929711/b54b80e8-6a1b-11e6-95fb-e2e9b74d09fa.PNG)
![capture3](https://cloud.githubusercontent.com/assets/21219058/17929717/ba1bd7d0-6a1b-11e6-81eb-46186d0c5e53.PNG)
![capture4](https://cloud.githubusercontent.com/assets/21219058/17929718/bd37f0ca-6a1b-11e6-8570-2c16182e773c.PNG)

Please correct this issue. 
Regards:
PHP developer.

**Comment by CreativeDream** [comment]
@arif-medialinker can you try please on [demo_page](http://filer.grandesign.md/#demos) - Example 3. If it works there, you will need to:
1. set to `null` the options `dragDrop` and `uploadFile`
or
2. update jQuery.filer plugin to v1.2

**Comment by arif-medialinker** [comment]
@CreativeDream  thanks for quick reply, Before posting this issue, I tried this demo Example 3, and get same results, with only last file, but not other files. 
let me try your suggestions.
Regards:

**Comment by arif-medialinker** [comment]
thanks latest Demo is working correctly.
